"""Add Blueprint table for blueprint caching

Revision ID: 4864d1c47cec
Revises: 9e9e70a4a06b
Create Date: 2026-01-17 04:02:59.038644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4864d1c47cec'
down_revision: Union[str, Sequence[str], None] = '9e9e70a4a06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blueprints')
    # ### end Alembic commands ###
