"""Add content_plans table for workflow planning

Revision ID: 4a0e3b03ab4c
Revises: 4864d1c47cec
Create Date: 2026-01-17 04:40:28.792508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0e3b03ab4c'
down_revision: Union[str, Sequence[str], None] = '4864d1c47cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_start_date', sa.String(length=10), nullable=False),
    sa.Column('pillar', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'GENERATED', 'CANCELLED', name='contentplanstatus'), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_plans')
    # ### end Alembic commands ###
